name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    # Set up Gradle in the specific directory
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
      with:
        build-root-directory: kociakWeb

    # Run the Gradle build command
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: kociakWeb

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    # Generate and submit dependency graph
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.0.0
      with:
        build-root-directory: kociakWeb
