name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # List files in the kociakWeb directory to verify gradlew location
      - name: List files for debugging
        run: ls -al kociakWeb/

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x kociakWeb/gradlew

      # Run the build using the Gradle wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        working-directory: kociakWeb
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: kociakWeb/build/reports/tests/test/index.html
